import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Package, Plus, Send, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { api } from '@fluxeme/shared/src/api/client';
import { PageHeader } from '@fluxeme/shared/src/components/PageHeader';
import { Button } from '@fluxeme/shared/src/components/ui/button';
import { Card, CardContent } from '@fluxeme/shared/src/components/ui/card';

type Plan = { id: string; code: string; name: string; accounting_mode: 'raw_tokens' | 'standardized_credits'; display_token_amount: number; total_units: number; input_credit_factor: number; output_credit_factor: number; cache_credit_factor: number; exhaustion_policy: 'package_then_wallet' | 'package_only'; priority: number; validity_days: number | null; status: string };
type Grant = { id: string; plan_id: string; plan_code: string; plan_name: string; user_id: string | null; team_id: string | null; accounting_mode: Plan['accounting_mode']; display_token_amount: number; total_units: number; consumed_units: number; reserved_units: number; priority: number; exhaustion_policy: Plan['exhaustion_policy']; status: string; expires_at: string | null };

export default function TokenPackages() {
  const qc = useQueryClient();
  const plans = useQuery({ queryKey: ['token-package-plans'], queryFn: () => api<Plan[]>('/admin/token-packages') });
  const grants = useQuery({ queryKey: ['token-package-grants'], queryFn: () => api<Grant[]>('/admin/token-packages/grants') });
  const [form, setForm] = useState({ code: '', name: '', accounting_mode: 'raw_tokens', display_token_amount: '10000000', total_units: '10000000', input_credit_factor: '1', output_credit_factor: '1', exhaustion_policy: 'package_then_wallet' });
  const [grantForm, setGrantForm] = useState({ plan_id: '', user_id: '', team_id: '', expires_at: '', note: '' });
  const createPlan = useMutation({ mutationFn: () => api<Plan>('/admin/token-packages', { method: 'POST', body: { ...form, display_token_amount: Number(form.display_token_amount), total_units: Number(form.total_units), input_credit_factor: Number(form.input_credit_factor), output_credit_factor: Number(form.output_credit_factor) } }), onSuccess: () => { qc.invalidateQueries({ queryKey: ['token-package-plans'] }); toast.success('Token package created'); }, onError: (error: Error) => toast.error(error.message) });
  const createGrant = useMutation({ mutationFn: () => api<{ grant: Grant }>('/admin/token-packages/grants', { method: 'POST', body: { plan_id: grantForm.plan_id, user_id: grantForm.user_id || undefined, team_id: grantForm.team_id || undefined, expires_at: grantForm.expires_at ? new Date(grantForm.expires_at).toISOString() : undefined, note: grantForm.note } }), onSuccess: () => { qc.invalidateQueries({ queryKey: ['token-package-grants'] }); toast.success('Token package granted'); }, onError: (error: Error) => toast.error(error.message) });
  const deletePlan = useMutation({ mutationFn: (id: string) => api<{ ok: boolean }>(`/admin/token-packages/${encodeURIComponent(id)}`, { method: 'DELETE' }), onSuccess: () => { qc.invalidateQueries({ queryKey: ['token-package-plans'] }); toast.success('Token package deleted'); }, onError: (error: Error) => toast.error(error.message) });
  const inputClass = 'h-9 rounded-md border bg-background px-3 text-sm';

  return (
    <div className="space-y-6 animate-fade-in">
      <PageHeader title="Token 资源包" description="创建原始 Token 或标准化 Credits 资源包，并发放给用户或团队。" />
      <Card><CardContent className="p-5 space-y-4"><div className="flex items-center gap-2 font-semibold"><Package className="size-4" />创建资源包计划</div><div className="grid grid-cols-1 md:grid-cols-3 gap-3"><input className={inputClass} placeholder="编码，如 token-10m" value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value })} /><input className={inputClass} placeholder="名称，如 1000 万 Token 包" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><select className={inputClass} value={form.accounting_mode} onChange={(e) => setForm({ ...form, accounting_mode: e.target.value })}><option value="raw_tokens">原始 Token 数量</option><option value="standardized_credits">标准化 Token Credits</option></select><input className={inputClass} type="number" min="1" value={form.display_token_amount} onChange={(e) => setForm({ ...form, display_token_amount: e.target.value })} /><input className={inputClass} type="number" min="1" value={form.total_units} onChange={(e) => setForm({ ...form, total_units: e.target.value })} /><select className={inputClass} value={form.exhaustion_policy} onChange={(e) => setForm({ ...form, exhaustion_policy: e.target.value })}><option value="package_then_wallet">资源包优先，钱包补足</option><option value="package_only">仅允许资源包</option></select></div>{form.accounting_mode === 'standardized_credits' && <div className="grid grid-cols-2 gap-3"><input className={inputClass} type="number" step="0.1" placeholder="输入系数" value={form.input_credit_factor} onChange={(e) => setForm({ ...form, input_credit_factor: e.target.value })} /><input className={inputClass} type="number" step="0.1" placeholder="输出系数" value={form.output_credit_factor} onChange={(e) => setForm({ ...form, output_credit_factor: e.target.value })} /></div>}<Button onClick={() => createPlan.mutate()} disabled={createPlan.isPending || !form.code || !form.name}><Plus className="size-4" />创建计划</Button></CardContent></Card>
      <Card><CardContent className="p-0 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-muted-foreground"><th className="text-left px-5 py-3">计划</th><th className="text-left px-5 py-3">模式</th><th className="text-right px-5 py-3">Token</th><th className="text-left px-5 py-3">策略</th><th className="text-left px-5 py-3">状态</th><th className="text-right px-5 py-3">操作</th></tr></thead><tbody>{plans.data?.map((plan) => <tr key={plan.id} className="border-b"><td className="px-5 py-3"><div className="font-medium">{plan.name}</div><div className="text-xs text-muted-foreground">{plan.code}</div></td><td className="px-5 py-3">{plan.accounting_mode === 'raw_tokens' ? '原始 Token 数量' : '标准化 Token Credits'}</td><td className="px-5 py-3 text-right">{plan.display_token_amount.toLocaleString()}</td><td className="px-5 py-3">{plan.exhaustion_policy === 'package_then_wallet' ? '资源包优先，钱包补足' : '仅允许资源包'}</td><td className="px-5 py-3">{plan.status}</td><td className="px-5 py-3 text-right"><Button variant="destructive" size="xs" onClick={() => { if (window.confirm(`删除计划 ${plan.name}？`)) deletePlan.mutate(plan.id); }} disabled={deletePlan.isPending}><Trash2 className="size-3" /></Button></td></tr>)}</tbody></table></CardContent></Card>
      <Card><CardContent className="p-5 space-y-4"><div className="flex items-center gap-2 font-semibold"><Send className="size-4" />发放资源包</div><div className="grid grid-cols-1 md:grid-cols-4 gap-3"><select className={inputClass} value={grantForm.plan_id} onChange={(e) => setGrantForm({ ...grantForm, plan_id: e.target.value })}><option value="">选择计划</option>{plans.data?.map((plan) => <option key={plan.id} value={plan.id}>{plan.name}</option>)}</select><input className={inputClass} placeholder="用户 ID（二选一）" value={grantForm.user_id} onChange={(e) => setGrantForm({ ...grantForm, user_id: e.target.value, team_id: '' })} /><input className={inputClass} placeholder="团队 ID（二选一）" value={grantForm.team_id} onChange={(e) => setGrantForm({ ...grantForm, team_id: e.target.value, user_id: '' })} /><input className={inputClass} type="datetime-local" value={grantForm.expires_at} onChange={(e) => setGrantForm({ ...grantForm, expires_at: e.target.value })} /></div><Button onClick={() => createGrant.mutate()} disabled={createGrant.isPending || !grantForm.plan_id || (!grantForm.user_id && !grantForm.team_id)}><Send className="size-4" />发放</Button></CardContent></Card>
      <Card><CardContent className="p-0 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-muted-foreground"><th className="text-left px-5 py-3">资源包计划</th><th className="text-left px-5 py-3">Grant</th><th className="text-left px-5 py-3">归属</th><th className="text-right px-5 py-3">剩余单位</th><th className="text-left px-5 py-3">有效期</th></tr></thead><tbody>{grants.data?.map((grant) => <tr key={grant.id} className="border-b"><td className="px-5 py-3"><div className="font-medium">{grant.plan_name}</div><div className="text-xs text-muted-foreground">{grant.plan_code}</div></td><td className="px-5 py-3 font-mono text-xs">{grant.id.slice(0, 12)}…</td><td className="px-5 py-3">{grant.user_id || grant.team_id}</td><td className="px-5 py-3 text-right">{Math.max(0, grant.total_units - grant.consumed_units - grant.reserved_units).toLocaleString()}</td><td className="px-5 py-3">{grant.expires_at ? new Date(grant.expires_at).toLocaleDateString() : '—'}</td></tr>)}</tbody></table></CardContent></Card>
    </div>
  );
}
